apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        executeinc/jx3-kubernetes: true
        executeinc/node-http-jx-quickstart: true
        ksully-execute/node-http-jx-quickstart: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        executeinc/jx3-kubernetes: merge
        executeinc/node-http-jx-quickstart: merge
        ksully-execute/node-http-jx-quickstart: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - executeinc/jx3-kubernetes
        - executeinc/node-http-jx-quickstart
        - ksully-execute/node-http-jx-quickstart
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - executeinc/jx3-kubernetes
        - executeinc/node-http-jx-quickstart
        - ksully-execute/node-http-jx-quickstart
      target_url: http://dashboard-jx.jx.executeinc.com
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
